### PR TITLE
add processor logic in common rake task

### PR DESCRIPTION
**Pull request by visu-suganya**
## Changes in this PR
- Added logic to call already available rake task when processor used with parallelism

## How to use
- I will take 0 if no processor used/passed

### CODE REVIEW

**Comment by visu-suganya** [comment]
@jkmfv this will help in many projects without adding separate rake files

**Comment by nhthach** [comment]
> @jkmfv this will help in many projects without adding separate rake files
> 
> Also please confirm whether updating version number with this PR will publish the changes or do we need to raise one more PR with version update after merging this ?

Hi @visu-suganya 
I used this branch to check and same it work well. ref: https://github.com/moneyforward/ex_web/pull/61255/files
But I wonder when we will publish this update.  Do these projects use this that need to update with the new syntax?  🤔 
```
bundle exec rake "simplecov:report_coverage[parallelism,processors]
````

**Comment by visu-suganya** [comment]
@nhthach
Thanks for the verification. Yes. The projects which uses this code doesn't need extra rake file to merge the reports with processors.

> Do these projects use this that need to update with the new syntax?
But make sure the the reports from parallel run should be in `./coverage_results/.resultset*.json` as this path used in merging the reports here.

**Review by nhthach — APPROVED** [review]
LGTM. Thanks so much

**Pull request merged**
